name: CI
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install/Update  build dependencies
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          curl -sL https://install.python-poetry.org | python -
      - name: Update Pip
        run: poetry run pip install -U pip setuptools
      - name: Install Dependencies
        run: poetry install
      - uses: pre-commit/action@v3.0.0

  linkcheck:
    name: Docs-Linkcheck
    runs-on: ubuntu-20.04
    env:
      ON_CI: true
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry pyparsing==3.0.4
      - name: Run LinkCheck
        run: nox --non-interactive --session linkcheck -- --full-trace