# This is a workflow to compile Sphinx sources on *main* branch and update *docs-build* branch

name: Compile Sphinx source and update docs-build branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python 3.10.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Update pip
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: Pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Sphinx-PDF Generated Package
      run: |
        pip install -e .
    - name: Build and Commit
      uses: iSOLveIT/sphinx-pdf-generate-action@main
      with:
        documentation_path: ./docs
        requirements_path: ./docs/requirements.txt
        target_branch: gh-pages
        sphinx_version: 6.0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
